# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2f62b807102ed97eb68e6cb8c28da8e54807cc036c9313313abe2f78343f3b26b09cf875807ad9444da5c1adb0d5b21109d8d55113dcfde3857c9f0bde87fe9

test:
  secret_key_base: 382b680156f30492c29da2a33e62ad6d858f79f93bc4bd550a92b84f2047e6444cfdfed17082038396a27d47ff192b77087158939d78207805e758159870840e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
